#version: "3.8"
#services:
#  sql-server-db:
#    container_name: sql-server-db
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      - "ACCEPT_EULA=Y"
#      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
#    ports:
#      - "1433:1433"
#    volumes:
#      - ./data:/var/opt/mssql/data
#      - ./log:/var/opt/mssql/log
#      - ./secrets:/var/opt/mssql/secrets