#version: "3.8"
#services:
#  sql-server-db:
#    container_name: sql-server-db
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      - "ACCEPT_EULA=Y"
#      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
#    ports:
#      - "1433:1433"
#    volumes:
#      - ./data:/var/opt/mssql/data
#      - ./log:/var/opt/mssql/log
#      - ./secrets:/var/opt/mssql/secretsit
version: "3.9"
services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - testDb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/postgres
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  testDb-data: { }
  liquibase-migratinos: { }