spring:
  application:
    name: DockerDbProject
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testDb
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false

server:
  port: 8080